In [7]:
import pandas as pd

In [9]:
pd.__version__

'0.22.0'

In [10]:
pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.4.final.0
python-bits: 64
OS: Darwin
OS-release: 17.4.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_CA.UTF-8
LOCALE: en_CA.UTF-8

pandas: 0.22.0
pytest: None
pip: 9.0.1
setuptools: 28.8.0
Cython: None
numpy: 1.14.1
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: None
patsy: None
dateutil: 2.6.1
pytz: 2018.3
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.2
openpyxl: None
xlrd: 1.1.0
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

In [11]:
import pandas as pd

In [19]:
oo = pd.read_csv('/Users/joycechidiadi/Desktop/../Olympics.csv', skiprows=4)

In [88]:
oo.head()

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
0,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100m freestyle,M,Gold
1,Athens,1896,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100m freestyle,M,Silver
2,Athens,1896,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100m freestyle for sailors,M,Bronze
3,Athens,1896,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100m freestyle for sailors,M,Gold
4,Athens,1896,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100m freestyle for sailors,M,Silver

In [23]:
oo

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
0,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100m freestyle,M,Gold
1,Athens,1896,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100m freestyle,M,Silver
2,Athens,1896,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100m freestyle for sailors,M,Bronze
3,Athens,1896,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100m freestyle for sailors,M,Gold
4,Athens,1896,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100m freestyle for sailors,M,Silver
5,Athens,1896,Aquatics,Swimming,"CHOROPHAS, Efstathios",GRE,Men,1200m freestyle,M,Bronze
6,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,1200m freestyle,M,Gold
7,Athens,1896,Aquatics,Swimming,"ANDREOU, Joannis",GRE,Men,1200m freestyle,M,Silver
8,Athens,1896,Aquatics,Swimming,"CHOROPHAS, Efstathios",GRE,Men,400m freestyle,M,Bronze
9,Athens,1896,Aquatics,Swimming,"NEUMANN, Paul",AUT,Men,400m freestyle,M,Gold
10,Athens,1896,Aquatics,Swimming,"PEPANOS, Antonios",GRE,Men,400m freestyle,M,Silver
11,Athens,1896,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze
12,Athens,1896,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze
13,Athens,1896,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold
14,Athens,1896,Athletics,Athletics,"HOFMANN, Fritz",GER,Men,100m,M,Silver
15,Athens,1896,Athletics,Athletics,"CURTIS, Thomas",USA,Men,110m hurdles,M,Gold
16,Athens,1896,Athletics,Athletics,"GOULDING, Grantley",GBR,Men,110m hurdles,M,Silver
17,Athens,1896,Athletics,Athletics,"LERMUSIAUX, Albin",FRA,Men,1500m,M,Bronze
18,Athens,1896,Athletics,Athletics,"FLACK, Edwin",AUS,Men,1500m,M,Gold
19,Athens,1896,Athletics,Athletics,"BLAKE, Arthur",USA,Men,1500m,M,Silver
20,Athens,1896,Athletics,Athletics,"GMELIN, Charles",GBR,Men,400m,M,Bronze
21,Athens,1896,Athletics,Athletics,"BURKE, Thomas",USA,Men,400m,M,Gold
22,Athens,1896,Athletics,Athletics,"JAMISON, Herbert",USA,Men,400m,M,Silver
23,Athens,1896,Athletics,Athletics,"GOLEMIS, Dimitrios",GRE,Men,800m,M,Bronze
24,Athens,1896,Athletics,Athletics,"FLACK, Edwin",AUS,Men,800m,M,Gold
25,Athens,1896,Athletics,Athletics,"DANI, Nandor",HUN,Men,800m,M,Silver
26,Athens,1896,Athletics,Athletics,"VERSIS, Sotirios",GRE,Men,discus throw,M,Bronze
27,Athens,1896,Athletics,Athletics,"GARRETT, Robert",USA,Men,discus throw,M,Gold
28,Athens,1896,Athletics,Athletics,"PARASKEVOPOULOS, Panagiotis",GRE,Men,discus throw,M,Silver
29,Athens,1896,Athletics,Athletics,"CLARK, Ellery",USA,Men,high jump,M,Gold
...,...,...,...,...,...,...,...,...,...,...
29186,Beijing,2008,Wrestling,Wrestling Free.,"MUTALIMOV, Marid",KAZ,Men,96 - 120kg,M,Bronze
29187,Beijing,2008,Wrestling,Wrestling Free.,"TAYMAZOV, Artur",UZB,Men,96 - 120kg,M,Gold
29188,Beijing,2008,Wrestling,Wrestling Free.,"AKHMEDOV, Bakhtiyar",RUS,Men,96 - 120kg,M,Silver
29189,Beijing,2008,Wrestling,Wrestling Gre-R,"AMOYAN, Roman",ARM,Men,- 55kg,M,Bronze
29190,Beijing,2008,Wrestling,Wrestling Gre-R,"PARK, Eun-Chul",KOR,Men,- 55kg,M,Bronze
29191,Beijing,2008,Wrestling,Wrestling Gre-R,"MANKIEV, Nazyr",RUS,Men,- 55kg,M,Gold
29192,Beijing,2008,Wrestling,Wrestling Gre-R,"BAYRAMOV, Rovshan",AZE,Men,- 55kg,M,Silver
29193,Beijing,2008,Wrestling,Wrestling Gre-R,"TENGIZBAYEV, Nurbakyt",KAZ,Men,55 - 60kg,M,Bronze
29194,Beijing,2008,Wrestling,Wrestling Gre-R,"TIUMENBAEV, Ruslan",KGZ,Men,55 - 60kg,M,Bronze
29195,Beijing,2008,Wrestling,Wrestling Gre-R,"ALBIEV, Islam-Beka",RUS,Men,55 - 60kg,M,Gold
29196,Beijing,2008,Wrestling,Wrestling Gre-R,"RAHIMOV, Vitaliy",AZE,Men,55 - 60kg,M,Silver
29197,Beijing,2008,Wrestling,Wrestling Gre-R,"SIAMIONAU, Mikhail",BLR,Men,60 - 66kg,M,Bronze
29198,Beijing,2008,Wrestling,Wrestling Gre-R,"VARDANYAN, Armen",UKR,Men,60 - 66kg,M,Bronze
29199,Beijing,2008,Wrestling,Wrestling Gre-R,"GUENOT, Steeve",FRA,Men,60 - 66kg,M,Gold
29200,Beijing,2008,Wrestling,Wrestling Gre-R,"BEGALIEV, Kanatbek",KGZ,Men,60 - 66kg,M,Silver
29201,Beijing,2008,Wrestling,Wrestling Gre-R,"GUENOT, Christophe",FRA,Men,66 - 74kg,M,Bronze
29202,Beijing,2008,Wrestling,Wrestling Gre-R,"YANAKIEV, Yavor",BUL,Men,66 - 74kg,M,Bronze
29203,Beijing,2008,Wrestling,Wrestling Gre-R,"KVIRKELIA, Manuchar",GEO,Men,66 - 74kg,M,Gold
29204,Beijing,2008,Wrestling,Wrestling Gre-R,"CHANG, Yongxiang",CHN,Men,66 - 74kg,M,Silver
29205,Beijing,2008,Wrestling,Wrestling Gre-R,"AVLUCA, Nazmi",TUR,Men,74 - 84kg,M,Bronze
29206,Beijing,2008,Wrestling,Wrestling Gre-R,"MINGUZZI, Andrea",ITA,Men,74 - 84kg,M,Gold
29207,Beijing,2008,Wrestling,Wrestling Gre-R,"FODOR, Zoltan",HUN,Men,74 - 84kg,M,Silver
29208,Beijing,2008,Wrestling,Wrestling Gre-R,"MAMBETOV, Asset",KAZ,Men,84 - 96kg,M,Bronze
29209,Beijing,2008,Wrestling,Wrestling Gre-R,"WHEELER, Adam",USA,Men,84 - 96kg,M,Bronze
29210,Beijing,2008,Wrestling,Wrestling Gre-R,"KHUSHTOV, Aslanbek",RUS,Men,84 - 96kg,M,Gold
29211,Beijing,2008,Wrestling,Wrestling Gre-R,"ENGLICH, Mirko",GER,Men,84 - 96kg,M,Silver
29212,Beijing,2008,Wrestling,Wrestling Gre-R,"MIZGAITIS, Mindaugas",LTU,Men,96 - 120kg,M,Bronze
29213,Beijing,2008,Wrestling,Wrestling Gre-R,"PATRIKEEV, Yuri",ARM,Men,96 - 120kg,M,Bronze
29214,Beijing,2008,Wrestling,Wrestling Gre-R,"LOPEZ, Mijain",CUB,Men,96 - 120kg,M,Gold
29215,Beijing,2008,Wrestling,Wrestling Gre-R,"BAROEV, Khasan",RUS,Men,96 - 120kg,M,Silver

In [89]:
import matplotlib.pyplot as plt

In [27]:
oo['City']

0         Athens
1         Athens
2         Athens
3         Athens
4         Athens
5         Athens
6         Athens
7         Athens
8         Athens
9         Athens
10        Athens
11        Athens
12        Athens
13        Athens
14        Athens
15        Athens
16        Athens
17        Athens
18        Athens
19        Athens
20        Athens
21        Athens
22        Athens
23        Athens
24        Athens
25        Athens
26        Athens
27        Athens
28        Athens
29        Athens
          ...
29186    Beijing
29187    Beijing
29188    Beijing
29189    Beijing
29190    Beijing
29191    Beijing
29192    Beijing
29193    Beijing
29194    Beijing
29195    Beijing
29196    Beijing
29197    Beijing
29198    Beijing
29199    Beijing
29200    Beijing
29201    Beijing
29202    Beijing
29203    Beijing
29204    Beijing
29205    Beijing
29206    Beijing
29207    Beijing
29208    Beijing
29209    Beijing
29210    Beijing
29211    Beijing
29212    Beijing
29213    Beijing
29214    Beijing
29215    Beijing
Name: City, Length: 29216, dtype: object

In [29]:
oo.Athlete

0                      HAJOS, Alfred
1                   HERSCHMANN, Otto
2                  DRIVAS, Dimitrios
3                 MALOKINIS, Ioannis
4                 CHASAPIS, Spiridon
5              CHOROPHAS, Efstathios
6                      HAJOS, Alfred
7                   ANDREOU, Joannis
8              CHOROPHAS, Efstathios
9                      NEUMANN, Paul
10                 PEPANOS, Antonios
11                     LANE, Francis
12                  SZOKOLYI, Alajos
13                     BURKE, Thomas
14                    HOFMANN, Fritz
15                    CURTIS, Thomas
16                GOULDING, Grantley
17                 LERMUSIAUX, Albin
18                      FLACK, Edwin
19                     BLAKE, Arthur
20                   GMELIN, Charles
21                     BURKE, Thomas
22                  JAMISON, Herbert
23                GOLEMIS, Dimitrios
24                      FLACK, Edwin
25                      DANI, Nandor
26                  VERSIS, Sotirios
27                   GARRETT, Robert
28       PARASKEVOPOULOS, Panagiotis
29                     CLARK, Ellery
                    ...
29186               MUTALIMOV, Marid
29187                TAYMAZOV, Artur
29188            AKHMEDOV, Bakhtiyar
29189                  AMOYAN, Roman
29190                 PARK, Eun-Chul
29191                 MANKIEV, Nazyr
29192              BAYRAMOV, Rovshan
29193          TENGIZBAYEV, Nurbakyt
29194             TIUMENBAEV, Ruslan
29195             ALBIEV, Islam-Beka
29196               RAHIMOV, Vitaliy
29197             SIAMIONAU, Mikhail
29198               VARDANYAN, Armen
29199                 GUENOT, Steeve
29200             BEGALIEV, Kanatbek
29201             GUENOT, Christophe
29202                YANAKIEV, Yavor
29203            KVIRKELIA, Manuchar
29204               CHANG, Yongxiang
29205                  AVLUCA, Nazmi
29206               MINGUZZI, Andrea
29207                  FODOR, Zoltan
29208                MAMBETOV, Asset
29209                  WHEELER, Adam
29210             KHUSHTOV, Aslanbek
29211                 ENGLICH, Mirko
29212           MIZGAITIS, Mindaugas
29213                PATRIKEEV, Yuri
29214                  LOPEZ, Mijain
29215                 BAROEV, Khasan
Name: Athlete, Length: 29216, dtype: object

In [31]:
oo['Athlete']

0                      HAJOS, Alfred
1                   HERSCHMANN, Otto
2                  DRIVAS, Dimitrios
3                 MALOKINIS, Ioannis
4                 CHASAPIS, Spiridon
5              CHOROPHAS, Efstathios
6                      HAJOS, Alfred
7                   ANDREOU, Joannis
8              CHOROPHAS, Efstathios
9                      NEUMANN, Paul
10                 PEPANOS, Antonios
11                     LANE, Francis
12                  SZOKOLYI, Alajos
13                     BURKE, Thomas
14                    HOFMANN, Fritz
15                    CURTIS, Thomas
16                GOULDING, Grantley
17                 LERMUSIAUX, Albin
18                      FLACK, Edwin
19                     BLAKE, Arthur
20                   GMELIN, Charles
21                     BURKE, Thomas
22                  JAMISON, Herbert
23                GOLEMIS, Dimitrios
24                      FLACK, Edwin
25                      DANI, Nandor
26                  VERSIS, Sotirios
27                   GARRETT, Robert
28       PARASKEVOPOULOS, Panagiotis
29                     CLARK, Ellery
                    ...
29186               MUTALIMOV, Marid
29187                TAYMAZOV, Artur
29188            AKHMEDOV, Bakhtiyar
29189                  AMOYAN, Roman
29190                 PARK, Eun-Chul
29191                 MANKIEV, Nazyr
29192              BAYRAMOV, Rovshan
29193          TENGIZBAYEV, Nurbakyt
29194             TIUMENBAEV, Ruslan
29195             ALBIEV, Islam-Beka
29196               RAHIMOV, Vitaliy
29197             SIAMIONAU, Mikhail
29198               VARDANYAN, Armen
29199                 GUENOT, Steeve
29200             BEGALIEV, Kanatbek
29201             GUENOT, Christophe
29202                YANAKIEV, Yavor
29203            KVIRKELIA, Manuchar
29204               CHANG, Yongxiang
29205                  AVLUCA, Nazmi
29206               MINGUZZI, Andrea
29207                  FODOR, Zoltan
29208                MAMBETOV, Asset
29209                  WHEELER, Adam
29210             KHUSHTOV, Aslanbek
29211                 ENGLICH, Mirko
29212           MIZGAITIS, Mindaugas
29213                PATRIKEEV, Yuri
29214                  LOPEZ, Mijain
29215                 BAROEV, Khasan
Name: Athlete, Length: 29216, dtype: object

In [32]:
type(oo.City)

pandas.core.series.Series

In [34]:
oo.NOC

0        HUN
1        AUT
2        GRE
3        GRE
4        GRE
5        GRE
6        HUN
7        GRE
8        GRE
9        AUT
10       GRE
11       USA
12       HUN
13       USA
14       GER
15       USA
16       GBR
17       FRA
18       AUS
19       USA
20       GBR
21       USA
22       USA
23       GRE
24       AUS
25       HUN
26       GRE
27       USA
28       GRE
29       USA
        ...
29186    KAZ
29187    UZB
29188    RUS
29189    ARM
29190    KOR
29191    RUS
29192    AZE
29193    KAZ
29194    KGZ
29195    RUS
29196    AZE
29197    BLR
29198    UKR
29199    FRA
29200    KGZ
29201    FRA
29202    BUL
29203    GEO
29204    CHN
29205    TUR
29206    ITA
29207    HUN
29208    KAZ
29209    USA
29210    RUS
29211    GER
29212    LTU
29213    ARM
29214    CUB
29215    RUS
Name: NOC, Length: 29216, dtype: object

In [40]:
type(oo[['Edition','City','Athlete','Medal']])

pandas.core.frame.DataFrame

In [48]:
oo = pd.read_csv('/Users/joycechidiadi/Desktop/Lynda_Courses/Olympics.csv', skiprows=4)

In [50]:
oo.shape

(29216, 10)

In [52]:
oo.tail()

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
29211,Beijing,2008,Wrestling,Wrestling Gre-R,"ENGLICH, Mirko",GER,Men,84 - 96kg,M,Silver
29212,Beijing,2008,Wrestling,Wrestling Gre-R,"MIZGAITIS, Mindaugas",LTU,Men,96 - 120kg,M,Bronze
29213,Beijing,2008,Wrestling,Wrestling Gre-R,"PATRIKEEV, Yuri",ARM,Men,96 - 120kg,M,Bronze
29214,Beijing,2008,Wrestling,Wrestling Gre-R,"LOPEZ, Mijain",CUB,Men,96 - 120kg,M,Gold
29215,Beijing,2008,Wrestling,Wrestling Gre-R,"BAROEV, Khasan",RUS,Men,96 - 120kg,M,Silver

In [54]:
oo.head()

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
0,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100m freestyle,M,Gold
1,Athens,1896,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100m freestyle,M,Silver
2,Athens,1896,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100m freestyle for sailors,M,Bronze
3,Athens,1896,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100m freestyle for sailors,M,Gold
4,Athens,1896,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100m freestyle for sailors,M,Silver

In [57]:
oo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29216 entries, 0 to 29215
Data columns (total 10 columns):
City            29216 non-null object
Edition         29216 non-null int64
Sport           29216 non-null object
Discipline      29216 non-null object
Athlete         29216 non-null object
NOC             29216 non-null object
Gender          29216 non-null object
Event           29216 non-null object
Event_gender    29216 non-null object
Medal           29216 non-null object
dtypes: int64(1), object(9)
memory usage: 2.2+ MB

In [58]:
oo.Edition.value_counts()

2008    2042
2000    2015
2004    1998
1996    1859
1992    1705
1988    1546
1984    1459
1980    1387
1976    1305
1920    1298
1972    1185
1968    1031
1964    1010
1952     889
1912     885
1956     885
1924     884
1960     882
1936     875
1948     814
1908     804
1928     710
1932     615
1900     512
1904     470
1896     151
Name: Edition, dtype: int64

In [61]:
oo.Gender.value_counts(ascending=True, dropna=False)

Women     7495
Men      21721
Name: Gender, dtype: int64

In [63]:
oo.Athlete.sort_values()

651                    AABYE, Edgar
2849          AALTONEN, Arvo Ossian
2852          AALTONEN, Arvo Ossian
7716       AALTONEN, Paavo Johannes
7730       AALTONEN, Paavo Johannes
7773       AALTONEN, Paavo Johannes
7709       AALTONEN, Paavo Johannes
8563       AALTONEN, Paavo Johannes
28460              AAMODT, Ragnhild
3436               AANING, Alf Lied
19062         AARDENBURG, Willemien
22769             AARDEWIJN, Pepijn
22267          AARONES, Ann Kristin
3437                  AAS, Karl Jan
2601           AAS, Thomas Valentin
28134              ABAJO, Jose Luis
27691              ABAKUMOVA, Maria
27983           ABALMASAU, Aliaksei
28417                    ABALO, Luc
24202         ABANDA ETONG, Patrice
21538            ABARCA, Jose Maria
27125                 ABAS, Stephen
16390     ABASCAL GARCIA, Alejandro
16806    ABASCAL GOMEZ, Jose Manuel
26049             ABASSOVA, Tamilla
28418                   ABATI, Joel
20477                   ABAY, Peter
6380             ABAY-NEMES, Oszkar
7003                  ABBA, Silvano
24757           ABBAGNALE, Agostino
                    ...
10948                ZYBINA, Galina
9128                 ZYBINA, Galina
8235                 ZYBINA, Galina
15817                ZYCH, Boguslaw
23611                ZYKINA, Olesya
25639                ZYKINA, Olesya
10596              ZÄHRINGER, Klaus
19282               ZÜHLKE, Steffen
18534                ZÜLOW, Andreas
1138                 ZÜRNER, Albert
1939                 ZÜRNER, Albert
15711           ÖRSTED, Hans-Henrik
2691                ÖRTEGREN, Ruben
3745                    ÖRVIG, Erik
3746                    ÖRVIG, Olav
3747                    ÖRVIG, Thor
3868                ÖSTENSEN, Östen
4009                ÖSTENSEN, Östen
3870                ÖSTENSEN, Östen
2730                ÖSTENSEN, Östen
3942                ÖSTENSEN, Östen
3737              ÖSTERVOLD, Henrik
3738           ÖSTERVOLD, Jan Olsen
3739      ÖSTERVOLD, Kristian Olsen
3740           ÖSTERVOLD, Ole Olsen
603                      ÖSTMO, Ole
608                      ÖSTMO, Ole
621                      ÖSTMO, Ole
596                      ÖSTMO, Ole
8051              ÖSTRAND, Per-Olof
Name: Athlete, Length: 29216, dtype: object

In [65]:
oo.sort_values(by=['Edition','Athlete'])

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
7,Athens,1896,Aquatics,Swimming,"ANDREOU, Joannis",GRE,Men,1200m freestyle,M,Silver
82,Athens,1896,Gymnastics,Artistic G.,"ANDRIAKOPOULOS, Nicolaos",GRE,Men,rope climbing,M,Gold
110,Athens,1896,Gymnastics,Artistic G.,"ANDRIAKOPOULOS, Nicolaos",GRE,Men,"team, parallel bars",M,Silver
111,Athens,1896,Gymnastics,Artistic G.,"ATHANASOPOULOS, Spyros",GRE,Men,"team, parallel bars",M,Silver
48,Athens,1896,Cycling,Cycling Road,"BATTEL, Edward",GBR,Men,individual road race,M,Bronze
19,Athens,1896,Athletics,Athletics,"BLAKE, Arthur",USA,Men,1500m,M,Silver
134,Athens,1896,Tennis,Tennis,"BOLAND, John",ZZX,Men,doubles,M,Gold
140,Athens,1896,Tennis,Tennis,"BOLAND, John",GBR,Men,singles,M,Gold
13,Athens,1896,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold
21,Athens,1896,Athletics,Athletics,"BURKE, Thomas",USA,Men,400m,M,Gold
84,Athens,1896,Gymnastics,Artistic G.,"BÖCKER, Konrad",GER,Men,"team, horizontal bar",M,Gold
99,Athens,1896,Gymnastics,Artistic G.,"BÖCKER, Konrad",GER,Men,"team, parallel bars",M,Gold
66,Athens,1896,Fencing,Fencing,"CALLOT, Henri",FRA,Men,foil individual,M,Silver
4,Athens,1896,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100m freestyle for sailors,M,Silver
5,Athens,1896,Aquatics,Swimming,"CHOROPHAS, Efstathios",GRE,Men,1200m freestyle,M,Bronze
8,Athens,1896,Aquatics,Swimming,"CHOROPHAS, Efstathios",GRE,Men,400m freestyle,M,Bronze
148,Athens,1896,Wrestling,Wrestling Gre-R,"CHRISTOPOULOS, Stephanos",GRE,Men,open event,M,Bronze
95,Athens,1896,Gymnastics,Artistic G.,"CHRYSAPHIS, Ioannis",GRE,Men,"team, parallel bars",M,Bronze
29,Athens,1896,Athletics,Athletics,"CLARK, Ellery",USA,Men,high jump,M,Gold
33,Athens,1896,Athletics,Athletics,"CLARK, Ellery",USA,Men,long jump,M,Gold
30,Athens,1896,Athletics,Athletics,"CONNOLLY, James",USA,Men,high jump,M,Silver
32,Athens,1896,Athletics,Athletics,"CONNOLLY, James",USA,Men,long jump,M,Bronze
46,Athens,1896,Athletics,Athletics,"CONNOLLY, James",USA,Men,triple jump,M,Gold
15,Athens,1896,Athletics,Athletics,"CURTIS, Thomas",USA,Men,110m hurdles,M,Gold
38,Athens,1896,Athletics,Athletics,"DAMASKOS, Evangelos",GRE,Men,pole vault,M,Bronze
25,Athens,1896,Athletics,Athletics,"DANI, Nandor",HUN,Men,800m,M,Silver
2,Athens,1896,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100m freestyle for sailors,M,Bronze
143,Athens,1896,Weightlifting,Weightlifting,"ELLIOTT, Launceston",GBR,Men,heavyweight - one hand lift,M,Gold
147,Athens,1896,Weightlifting,Weightlifting,"ELLIOTT, Launceston",GBR,Men,heavyweight - two hand lift,M,Silver
18,Athens,1896,Athletics,Athletics,"FLACK, Edwin",AUS,Men,1500m,M,Gold
...,...,...,...,...,...,...,...,...,...,...
28583,Beijing,2008,Hockey,Hockey,"ZHANG, Yimeng",CHN,Women,hockey,W,Silver
28940,Beijing,2008,Table Tennis,Table Tennis,"ZHANG, Yining",CHN,Women,singles,W,Gold
28956,Beijing,2008,Table Tennis,Table Tennis,"ZHANG, Yining",CHN,Women,team,W,Gold
27893,Beijing,2008,Boxing,Boxing,"ZHANG, Zhilei",CHN,Men,+ 91kg (super heavyweight),M,Silver
27340,Beijing,2008,Aquatics,Swimming,"ZHAO, Jing",CHN,Women,4x100m medley relay,W,Bronze
29074,Beijing,2008,Volleyball,Volleyball,"ZHAO, Ruirui",CHN,Women,volleyball,W,Bronze
28584,Beijing,2008,Hockey,Hockey,"ZHAO, Yudiao",CHN,Women,hockey,W,Silver
28999,Beijing,2008,Tennis,Tennis,"ZHENG, Jie",CHN,Women,doubles,W,Bronze
28641,Beijing,2008,Judo,Judo,"ZHITKEYEV, Askhat",KAZ,Men,90 - 100kg (half-heavyweight),M,Silver
28169,Beijing,2008,Fencing,Fencing,"ZHONG, Man",CHN,Men,sabre individual,M,Gold
27701,Beijing,2008,Athletics,Athletics,"ZHOU, Chunxiu",CHN,Women,marathon,W,Bronze
27176,Beijing,2008,Aquatics,Diving,"ZHOU, Luxin",CHN,Men,10m platform,M,Silver
29075,Beijing,2008,Volleyball,Volleyball,"ZHOU, Suhong",CHN,Women,volleyball,W,Bronze
28585,Beijing,2008,Hockey,Hockey,"ZHOU, Wanfeng",CHN,Women,hockey,W,Silver
27341,Beijing,2008,Aquatics,Swimming,"ZHOU, Yafei",CHN,Women,4x100m medley relay,W,Bronze
28191,Beijing,2008,Fencing,Fencing,"ZHOVNIR, Olha",UKR,Women,sabre team,W,Gold
28989,Beijing,2008,Taekwondo,Taekwondo,"ZHU, Guo",CHN,Men,68 - 80 kg,M,Bronze
27394,Beijing,2008,Aquatics,Swimming,"ZHU, Qianwei",CHN,Women,4x200m freestyle relay,W,Silver
28857,Beijing,2008,Shooting,Shooting,"ZHU, Qinan",CHN,Men,10m air rifle (60 shots),M,Silver
28396,Beijing,2008,Gymnastics,Rhythmic G.,"ZHUKOVA, Inna",BLR,Women,individual all-round,W,Silver
29172,Beijing,2008,Wrestling,Wrestling Free.,"ZLATEVA, Stanka",BUL,Women,63 - 72kg,W,Silver
28308,Beijing,2008,Gymnastics,Artistic G.,"ZOU, Kai",CHN,Men,floor exercises,M,Gold
28314,Beijing,2008,Gymnastics,Artistic G.,"ZOU, Kai",CHN,Men,horizontal bar,M,Gold
28342,Beijing,2008,Gymnastics,Artistic G.,"ZOU, Kai",CHN,Men,team competition,M,Gold
27900,Beijing,2008,Boxing,Boxing,"ZOU, Shiming",CHN,Men,48kg (light flywieght),M,Gold
28095,Beijing,2008,Equestrian,Dressage,"ZU-SAYN WITTGENSTEIN, Nathalie",DEN,Women,team,X,Bronze
28819,Beijing,2008,Sailing,Sailing,"ZUBARI, Shahar",ISR,Men,RS:X - Windsurfer,M,Bronze
28977,Beijing,2008,Taekwondo,Taekwondo,"ZUBCIC, Martina",CRO,Women,49 - 57 kg,W,Bronze
28387,Beijing,2008,Gymnastics,Rhythmic G.,"ZUEVA, Natalia",RUS,Women,group competition,W,Gold
29007,Beijing,2008,Tennis,Tennis,"ZVONAREVA, Vera",RUS,Women,singles,W,Bronze

In [67]:
oo.Medal == 'Gold'

0         True
1        False
2        False
3         True
4        False
5        False
6         True
7        False
8        False
9         True
10       False
11       False
12       False
13        True
14       False
15        True
16       False
17       False
18        True
19       False
20       False
21        True
22       False
23       False
24        True
25       False
26       False
27        True
28       False
29        True
         ...
29186    False
29187     True
29188    False
29189    False
29190    False
29191     True
29192    False
29193    False
29194    False
29195     True
29196    False
29197    False
29198    False
29199     True
29200    False
29201    False
29202    False
29203     True
29204    False
29205    False
29206     True
29207    False
29208    False
29209    False
29210     True
29211    False
29212    False
29213    False
29214     True
29215    False
Name: Medal, Length: 29216, dtype: bool

In [69]:
oo.head()

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
0,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100m freestyle,M,Gold
1,Athens,1896,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100m freestyle,M,Silver
2,Athens,1896,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100m freestyle for sailors,M,Bronze
3,Athens,1896,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100m freestyle for sailors,M,Gold
4,Athens,1896,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100m freestyle for sailors,M,Silver

In [72]:
oo[oo.Medal == 'Gold']

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
0,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100m freestyle,M,Gold
3,Athens,1896,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100m freestyle for sailors,M,Gold
6,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,1200m freestyle,M,Gold
9,Athens,1896,Aquatics,Swimming,"NEUMANN, Paul",AUT,Men,400m freestyle,M,Gold
13,Athens,1896,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold
15,Athens,1896,Athletics,Athletics,"CURTIS, Thomas",USA,Men,110m hurdles,M,Gold
18,Athens,1896,Athletics,Athletics,"FLACK, Edwin",AUS,Men,1500m,M,Gold
21,Athens,1896,Athletics,Athletics,"BURKE, Thomas",USA,Men,400m,M,Gold
24,Athens,1896,Athletics,Athletics,"FLACK, Edwin",AUS,Men,800m,M,Gold
27,Athens,1896,Athletics,Athletics,"GARRETT, Robert",USA,Men,discus throw,M,Gold
29,Athens,1896,Athletics,Athletics,"CLARK, Ellery",USA,Men,high jump,M,Gold
33,Athens,1896,Athletics,Athletics,"CLARK, Ellery",USA,Men,long jump,M,Gold
36,Athens,1896,Athletics,Athletics,"LOUIS, Spyridon",GRE,Men,marathon,M,Gold
40,Athens,1896,Athletics,Athletics,"HOYT, William Welles",USA,Men,pole vault,M,Gold
43,Athens,1896,Athletics,Athletics,"GARRETT, Robert",USA,Men,shot put,M,Gold
46,Athens,1896,Athletics,Athletics,"CONNOLLY, James",USA,Men,triple jump,M,Gold
49,Athens,1896,Cycling,Cycling Road,"KONSTANTINIDIS, Aristidis",GRE,Men,individual road race,M,Gold
51,Athens,1896,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold
54,Athens,1896,Cycling,Cycling Track,"MASSON, Paul",FRA,Men,10km,M,Gold
56,Athens,1896,Cycling,Cycling Track,"SCHMAL, Adolf",AUT,Men,12-hour race,M,Gold
59,Athens,1896,Cycling,Cycling Track,"MASSON, Paul",FRA,Men,1km time trial,M,Gold
62,Athens,1896,Cycling,Cycling Track,"MASSON, Paul",FRA,Men,Sprint indivual,M,Gold
65,Athens,1896,Fencing,Fencing,"GRAVELOTTE, Eugène-Henri",FRA,Men,foil individual,M,Gold
67,Athens,1896,Fencing,Fencing,"PYRGOS, Leonidas",GRE,Men,"foil, masters",M,Gold
70,Athens,1896,Fencing,Fencing,"GEORGIADIS, Ioannis",GRE,Men,sabre individual,M,Gold
72,Athens,1896,Gymnastics,Artistic G.,"WEINGÄRTNER, Hermann",GER,Men,horizontal bar,M,Gold
74,Athens,1896,Gymnastics,Artistic G.,"FLATOW, Alfred",GER,Men,parallel bars,M,Gold
76,Athens,1896,Gymnastics,Artistic G.,"ZUTTER, Louis",SUI,Men,pommel horse,M,Gold
79,Athens,1896,Gymnastics,Artistic G.,"MITROPOULOS, Ioannis",GRE,Men,rings,M,Gold
82,Athens,1896,Gymnastics,Artistic G.,"ANDRIAKOPOULOS, Nicolaos",GRE,Men,rope climbing,M,Gold
...,...,...,...,...,...,...,...,...,...,...
29110,Beijing,2008,Weightlifting,Weightlifting,"ARAMNAU, Andrei",BLR,Men,105kg,M,Gold
29113,Beijing,2008,Weightlifting,Weightlifting,"CHEN, Xiexia",CHN,Women,48kg,W,Gold
29116,Beijing,2008,Weightlifting,Weightlifting,"JAROENRATTANATARAKOON, Prapawadee",THA,Women,53kg,W,Gold
29119,Beijing,2008,Weightlifting,Weightlifting,"CHEN, Yanqing",CHN,Women,58kg,W,Gold
29122,Beijing,2008,Weightlifting,Weightlifting,"ZHANG, Xiangxiang",CHN,Men,62kg,M,Gold
29125,Beijing,2008,Weightlifting,Weightlifting,"PAK, Hyon Suk",PRK,Women,63kg,W,Gold
29128,Beijing,2008,Weightlifting,Weightlifting,"LIAO, Hui",CHN,Men,69kg,M,Gold
29131,Beijing,2008,Weightlifting,Weightlifting,"LIU, Chunhong",CHN,Women,69kg,W,Gold
29134,Beijing,2008,Weightlifting,Weightlifting,"CAO, Lei",CHN,Women,75kg,W,Gold
29137,Beijing,2008,Weightlifting,Weightlifting,"SA, Jaehyouk",KOR,Men,77kg,M,Gold
29140,Beijing,2008,Weightlifting,Weightlifting,"LU, Yong",CHN,Men,85kg,M,Gold
29143,Beijing,2008,Weightlifting,Weightlifting,"ILIN, Ilya",KAZ,Men,94kg,M,Gold
29147,Beijing,2008,Wrestling,Wrestling Free.,"HUYNH, Carol",CAN,Women,- 48kg,W,Gold
29151,Beijing,2008,Wrestling,Wrestling Free.,"CEJUDO, Henry",USA,Men,- 55kg,M,Gold
29155,Beijing,2008,Wrestling,Wrestling Free.,"YOSHIDA, Saori",JPN,Women,48 - 55kg,W,Gold
29159,Beijing,2008,Wrestling,Wrestling Free.,"BATIROV, Mavlet",RUS,Men,55 - 60kg,M,Gold
29163,Beijing,2008,Wrestling,Wrestling Free.,"ICHO, Kaori",JPN,Women,55 - 63kg,W,Gold
29167,Beijing,2008,Wrestling,Wrestling Free.,"SAHIN, Ramazan",TUR,Men,60 - 66kg,M,Gold
29171,Beijing,2008,Wrestling,Wrestling Free.,"WANG, Jiao",CHN,Women,63 - 72kg,W,Gold
29175,Beijing,2008,Wrestling,Wrestling Free.,"SAYTIEV, Buvaysa",RUS,Men,66 - 74kg,M,Gold
29179,Beijing,2008,Wrestling,Wrestling Free.,"MINDORASHVILI, Revazi",GEO,Men,74 - 84kg,M,Gold
29183,Beijing,2008,Wrestling,Wrestling Free.,"MURADOV, Shirvani",RUS,Men,84 - 96kg,M,Gold
29187,Beijing,2008,Wrestling,Wrestling Free.,"TAYMAZOV, Artur",UZB,Men,96 - 120kg,M,Gold
29191,Beijing,2008,Wrestling,Wrestling Gre-R,"MANKIEV, Nazyr",RUS,Men,- 55kg,M,Gold
29195,Beijing,2008,Wrestling,Wrestling Gre-R,"ALBIEV, Islam-Beka",RUS,Men,55 - 60kg,M,Gold
29199,Beijing,2008,Wrestling,Wrestling Gre-R,"GUENOT, Steeve",FRA,Men,60 - 66kg,M,Gold
29203,Beijing,2008,Wrestling,Wrestling Gre-R,"KVIRKELIA, Manuchar",GEO,Men,66 - 74kg,M,Gold
29206,Beijing,2008,Wrestling,Wrestling Gre-R,"MINGUZZI, Andrea",ITA,Men,74 - 84kg,M,Gold
29210,Beijing,2008,Wrestling,Wrestling Gre-R,"KHUSHTOV, Aslanbek",RUS,Men,84 - 96kg,M,Gold
29214,Beijing,2008,Wrestling,Wrestling Gre-R,"LOPEZ, Mijain",CUB,Men,96 - 120kg,M,Gold

In [74]:
oo[(oo.Medal == 'Gold') & (oo.Gender == 'Women')]

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
417,Paris,1900,Golf,Golf,"ABBOTT, Margaret Ives",USA,Women,individual,W,Gold
641,Paris,1900,Tennis,Tennis,"COOPER, Charlotte",GBR,Women,mixed doubles,X,Gold
649,Paris,1900,Tennis,Tennis,"COOPER, Charlotte",GBR,Women,singles,W,Gold
710,St Louis,1904,Archery,Archery,"HOWELL, Matilda Scott",USA,Women,double columbia round (50y - 40y - 30y),W,Gold
713,St Louis,1904,Archery,Archery,"HOWELL, Matilda Scott",USA,Women,double national round (60y - 50y),W,Gold
730,St Louis,1904,Archery,Archery,"HOWELL, Matilda Scott",USA,Women,teams FITA round,W,Gold
731,St Louis,1904,Archery,Archery,"POLLOCK, Jessie",USA,Women,teams FITA round,W,Gold
732,St Louis,1904,Archery,Archery,"TAYLOR, Louise",USA,Women,teams FITA round,W,Gold
733,St Louis,1904,Archery,Archery,"WOODRUFF, Laura",USA,Women,teams FITA round,W,Gold
1185,London,1908,Archery,Archery,"NEWALL, Sybil Fenton Quenni",GBR,Women,national round (60y - 50y),W,Gold
1843,London,1908,Skating,Figure skating,"SYERS, Florence",GBR,Women,individual,W,Gold
1849,London,1908,Skating,Figure skating,"HÜBLER, Anna",GER,Women,pairs,X,Gold
1870,London,1908,Tennis,Tennis,"CHAMBERS, Dorothy Katherine",GBR,Women,singles,W,Gold
1876,London,1908,Tennis,Tennis,"EASTLAKE-SMITH, Gwendoline",GBR,Women,singles indoor,W,Gold
1941,Stockholm,1912,Aquatics,Diving,"JOHANSSON, Greta",SWE,Women,10m platform,W,Gold
1956,Stockholm,1912,Aquatics,Swimming,"DURACK, Fanny",ANZ,Women,100m freestyle,W,Gold
1974,Stockholm,1912,Aquatics,Swimming,"FLETCHER, Jennie",GBR,Women,4x100m freestyle relay,W,Gold
1975,Stockholm,1912,Aquatics,Swimming,"MOORE, Isabella Mary",GBR,Women,4x100m freestyle relay,W,Gold
1976,Stockholm,1912,Aquatics,Swimming,"SPEIRS, Annie",GBR,Women,4x100m freestyle relay,W,Gold
1977,Stockholm,1912,Aquatics,Swimming,"STEER, Irene",GBR,Women,4x100m freestyle relay,W,Gold
2771,Stockholm,1912,Tennis,Tennis,"KÖRING, Dora",GER,Women,mixed doubles,X,Gold
2777,Stockholm,1912,Tennis,Tennis,"HANNAM, Edith Margaret",GBR,Women,mixed doubles indoor,X,Gold
2783,Stockholm,1912,Tennis,Tennis,"BROQUEDIS, Marguerite",FRA,Women,singles,W,Gold
2789,Stockholm,1912,Tennis,Tennis,"HANNAM, Edith Margaret",GBR,Women,singles indoor,W,Gold
2826,Antwerp,1920,Aquatics,Diving,"FRYLAND CLAUSEN, Stefani",DEN,Women,10m platform,W,Gold
2832,Antwerp,1920,Aquatics,Diving,"RIGGIN, Aileen",USA,Women,3m springboard,W,Gold
2844,Antwerp,1920,Aquatics,Swimming,"BLEIBTREY, Ethelda",USA,Women,100m freestyle,W,Gold
2859,Antwerp,1920,Aquatics,Swimming,"BLEIBTREY, Ethelda",USA,Women,400m freestyle,W,Gold
2865,Antwerp,1920,Aquatics,Swimming,"BLEIBTREY, Ethelda",USA,Women,4x100m freestyle relay,W,Gold
2866,Antwerp,1920,Aquatics,Swimming,"GUEST, Irene",USA,Women,4x100m freestyle relay,W,Gold
...,...,...,...,...,...,...,...,...,...,...
28982,Beijing,2008,Taekwondo,Taekwondo,"HWANG, Kyung Sun",KOR,Women,57 - 67 kg,W,Gold
29000,Beijing,2008,Tennis,Tennis,"WILLIAMS, Serena",USA,Women,doubles,W,Gold
29001,Beijing,2008,Tennis,Tennis,"WILLIAMS, Venus",USA,Women,doubles,W,Gold
29008,Beijing,2008,Tennis,Tennis,"DEMENTIEVA, Elena",RUS,Women,singles,W,Gold
29014,Beijing,2008,Triathlon,Triathlon,"SNOWSILL, Emma",AUS,Women,Individual,W,Gold
29024,Beijing,2008,Volleyball,Beach volley.,"MAY-TREANOR, Misty",USA,Women,beach volleyball,W,Gold
29025,Beijing,2008,Volleyball,Beach volley.,"WALSH, Kerri",USA,Women,beach volleyball,W,Gold
29076,Beijing,2008,Volleyball,Volleyball,"ALBUQUERQUE, Carolina",BRA,Women,volleyball,W,Gold
29077,Beijing,2008,Volleyball,Volleyball,"CARVALHO, Jaqueline",BRA,Women,volleyball,W,Gold
29078,Beijing,2008,Volleyball,Volleyball,"CASTRO, Sheilla",BRA,Women,volleyball,W,Gold
29079,Beijing,2008,Volleyball,Volleyball,"CLAUDINO, Fabiana",BRA,Women,volleyball,W,Gold
29080,Beijing,2008,Volleyball,Volleyball,"DE OLIVEIRA, Fabiana",BRA,Women,volleyball,W,Gold
29081,Beijing,2008,Volleyball,Volleyball,"GONZAGA, Welissa",BRA,Women,volleyball,W,Gold
29082,Beijing,2008,Volleyball,Volleyball,"MENEZES, Thaisa",BRA,Women,volleyball,W,Gold
29083,Beijing,2008,Volleyball,Volleyball,"MENEZES, Valeska",BRA,Women,volleyball,W,Gold
29084,Beijing,2008,Volleyball,Volleyball,"OLIVEIRA, Walewska",BRA,Women,volleyball,W,Gold
29085,Beijing,2008,Volleyball,Volleyball,"PEQUENO, Paula",BRA,Women,volleyball,W,Gold
29086,Beijing,2008,Volleyball,Volleyball,"SOUZA, Helia",BRA,Women,volleyball,W,Gold
29087,Beijing,2008,Volleyball,Volleyball,"STEINBRECHER, Marianne",BRA,Women,volleyball,W,Gold
29107,Beijing,2008,Weightlifting,Weightlifting,"JANG, Miran",KOR,Women,+ 75kg,W,Gold
29113,Beijing,2008,Weightlifting,Weightlifting,"CHEN, Xiexia",CHN,Women,48kg,W,Gold
29116,Beijing,2008,Weightlifting,Weightlifting,"JAROENRATTANATARAKOON, Prapawadee",THA,Women,53kg,W,Gold
29119,Beijing,2008,Weightlifting,Weightlifting,"CHEN, Yanqing",CHN,Women,58kg,W,Gold
29125,Beijing,2008,Weightlifting,Weightlifting,"PAK, Hyon Suk",PRK,Women,63kg,W,Gold
29131,Beijing,2008,Weightlifting,Weightlifting,"LIU, Chunhong",CHN,Women,69kg,W,Gold
29134,Beijing,2008,Weightlifting,Weightlifting,"CAO, Lei",CHN,Women,75kg,W,Gold
29147,Beijing,2008,Wrestling,Wrestling Free.,"HUYNH, Carol",CAN,Women,- 48kg,W,Gold
29155,Beijing,2008,Wrestling,Wrestling Free.,"YOSHIDA, Saori",JPN,Women,48 - 55kg,W,Gold
29163,Beijing,2008,Wrestling,Wrestling Free.,"ICHO, Kaori",JPN,Women,55 - 63kg,W,Gold
29171,Beijing,2008,Wrestling,Wrestling Free.,"WANG, Jiao",CHN,Women,63 - 72kg,W,Gold

In [77]:
oo.head()

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
0,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100m freestyle,M,Gold
1,Athens,1896,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100m freestyle,M,Silver
2,Athens,1896,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100m freestyle for sailors,M,Bronze
3,Athens,1896,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100m freestyle for sailors,M,Gold
4,Athens,1896,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100m freestyle for sailors,M,Silver

In [80]:
oo[oo.Athlete.str.contains('Florence')]

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
1843,London,1908,Skating,Figure skating,"SYERS, Florence",GBR,Women,individual,W,Gold
1848,London,1908,Skating,Figure skating,"SYERS, Florence",GBR,Women,pairs,X,Bronze
4173,Paris,1924,Aquatics,Swimming,"BARKER, Florence",GBR,Women,4x100m freestyle relay,W,Silver
8162,Helsinki,1952,Athletics,Athletics,"FOULDS-PAUL, June Florence",GBR,Women,4x100m relay,W,Bronze
9060,Melbourne / Stockholm,1956,Athletics,Athletics,"FOULDS-PAUL, June Florence",GBR,Women,4x100m relay,W,Silver
10849,Tokyo,1964,Athletics,Athletics,"AMOORE-POLLOCK, Judith Florence",AUS,Women,400m,W,Bronze
16817,Los Angeles,1984,Athletics,Athletics,"GRIFFITH-JOYNER, Florence",USA,Women,200m,W,Silver
18287,Seoul,1988,Athletics,Athletics,"GRIFFITH-JOYNER, Florence",USA,Women,100m,W,Gold
18305,Seoul,1988,Athletics,Athletics,"GRIFFITH-JOYNER, Florence",USA,Women,200m,W,Gold
18347,Seoul,1988,Athletics,Athletics,"GRIFFITH-JOYNER, Florence",USA,Women,4x100m relay,W,Gold
18374,Seoul,1988,Athletics,Athletics,"GRIFFITH-JOYNER, Florence",USA,Women,4x400m relay,W,Silver

In [86]:
oo.head

<bound method NDFrame.head of           City  Edition      Sport       Discipline  \
0       Athens     1896   Aquatics         Swimming
1       Athens     1896   Aquatics         Swimming
2       Athens     1896   Aquatics         Swimming
3       Athens     1896   Aquatics         Swimming
4       Athens     1896   Aquatics         Swimming
5       Athens     1896   Aquatics         Swimming
6       Athens     1896   Aquatics         Swimming
7       Athens     1896   Aquatics         Swimming
8       Athens     1896   Aquatics         Swimming
9       Athens     1896   Aquatics         Swimming
10      Athens     1896   Aquatics         Swimming
11      Athens     1896  Athletics        Athletics
12      Athens     1896  Athletics        Athletics
13      Athens     1896  Athletics        Athletics
14      Athens     1896  Athletics        Athletics
15      Athens     1896  Athletics        Athletics
16      Athens     1896  Athletics        Athletics
17      Athens     1896  Athletics        Athletics
18      Athens     1896  Athletics        Athletics
19      Athens     1896  Athletics        Athletics
20      Athens     1896  Athletics        Athletics
21      Athens     1896  Athletics        Athletics
22      Athens     1896  Athletics        Athletics
23      Athens     1896  Athletics        Athletics
24      Athens     1896  Athletics        Athletics
25      Athens     1896  Athletics        Athletics
26      Athens     1896  Athletics        Athletics
27      Athens     1896  Athletics        Athletics
28      Athens     1896  Athletics        Athletics
29      Athens     1896  Athletics        Athletics
...        ...      ...        ...              ...
29186  Beijing     2008  Wrestling  Wrestling Free.
29187  Beijing     2008  Wrestling  Wrestling Free.
29188  Beijing     2008  Wrestling  Wrestling Free.
29189  Beijing     2008  Wrestling  Wrestling Gre-R
29190  Beijing     2008  Wrestling  Wrestling Gre-R
29191  Beijing     2008  Wrestling  Wrestling Gre-R
29192  Beijing     2008  Wrestling  Wrestling Gre-R
29193  Beijing     2008  Wrestling  Wrestling Gre-R
29194  Beijing     2008  Wrestling  Wrestling Gre-R
29195  Beijing     2008  Wrestling  Wrestling Gre-R
29196  Beijing     2008  Wrestling  Wrestling Gre-R
29197  Beijing     2008  Wrestling  Wrestling Gre-R
29198  Beijing     2008  Wrestling  Wrestling Gre-R
29199  Beijing     2008  Wrestling  Wrestling Gre-R
29200  Beijing     2008  Wrestling  Wrestling Gre-R
29201  Beijing     2008  Wrestling  Wrestling Gre-R
29202  Beijing     2008  Wrestling  Wrestling Gre-R
29203  Beijing     2008  Wrestling  Wrestling Gre-R
29204  Beijing     2008  Wrestling  Wrestling Gre-R
29205  Beijing     2008  Wrestling  Wrestling Gre-R
29206  Beijing     2008  Wrestling  Wrestling Gre-R
29207  Beijing     2008  Wrestling  Wrestling Gre-R
29208  Beijing     2008  Wrestling  Wrestling Gre-R
29209  Beijing     2008  Wrestling  Wrestling Gre-R
29210  Beijing     2008  Wrestling  Wrestling Gre-R
29211  Beijing     2008  Wrestling  Wrestling Gre-R
29212  Beijing     2008  Wrestling  Wrestling Gre-R
29213  Beijing     2008  Wrestling  Wrestling Gre-R
29214  Beijing     2008  Wrestling  Wrestling Gre-R
29215  Beijing     2008  Wrestling  Wrestling Gre-R

                           Athlete  NOC Gender                       Event  \
0                    HAJOS, Alfred  HUN    Men              100m freestyle
1                 HERSCHMANN, Otto  AUT    Men              100m freestyle
2                DRIVAS, Dimitrios  GRE    Men  100m freestyle for sailors
3               MALOKINIS, Ioannis  GRE    Men  100m freestyle for sailors
4               CHASAPIS, Spiridon  GRE    Men  100m freestyle for sailors
5            CHOROPHAS, Efstathios  GRE    Men             1200m freestyle
6                    HAJOS, Alfred  HUN    Men             1200m freestyle
7                 ANDREOU, Joannis  GRE    Men             1200m freestyle
8            CHOROPHAS, Efstathios  GRE    Men              400m freestyle
9                    NEUMANN, Paul  AUT    Men              400m freestyle
10               PEPANOS, Antonios  GRE    Men              400m freestyle
11                   LANE, Francis  USA    Men                        100m
12                SZOKOLYI, Alajos  HUN    Men                        100m
13                   BURKE, Thomas  USA    Men                        100m
14                  HOFMANN, Fritz  GER    Men                        100m
15                  CURTIS, Thomas  USA    Men                110m hurdles
16              GOULDING, Grantley  GBR    Men                110m hurdles
17               LERMUSIAUX, Albin  FRA    Men                       1500m
18                    FLACK, Edwin  AUS    Men                       1500m
19                   BLAKE, Arthur  USA    Men                       1500m
20                 GMELIN, Charles  GBR    Men                        400m
21                   BURKE, Thomas  USA    Men                        400m
22                JAMISON, Herbert  USA    Men                        400m
23              GOLEMIS, Dimitrios  GRE    Men                        800m
24                    FLACK, Edwin  AUS    Men                        800m
25                    DANI, Nandor  HUN    Men                        800m
26                VERSIS, Sotirios  GRE    Men                discus throw
27                 GARRETT, Robert  USA    Men                discus throw
28     PARASKEVOPOULOS, Panagiotis  GRE    Men                discus throw
29                   CLARK, Ellery  USA    Men                   high jump
...                            ...  ...    ...                         ...
29186             MUTALIMOV, Marid  KAZ    Men                  96 - 120kg
29187              TAYMAZOV, Artur  UZB    Men                  96 - 120kg
29188          AKHMEDOV, Bakhtiyar  RUS    Men                  96 - 120kg
29189                AMOYAN, Roman  ARM    Men                      - 55kg
29190               PARK, Eun-Chul  KOR    Men                      - 55kg
29191               MANKIEV, Nazyr  RUS    Men                      - 55kg
29192            BAYRAMOV, Rovshan  AZE    Men                      - 55kg
29193        TENGIZBAYEV, Nurbakyt  KAZ    Men                   55 - 60kg
29194           TIUMENBAEV, Ruslan  KGZ    Men                   55 - 60kg
29195           ALBIEV, Islam-Beka  RUS    Men                   55 - 60kg
29196             RAHIMOV, Vitaliy  AZE    Men                   55 - 60kg
29197           SIAMIONAU, Mikhail  BLR    Men                   60 - 66kg
29198             VARDANYAN, Armen  UKR    Men                   60 - 66kg
29199               GUENOT, Steeve  FRA    Men                   60 - 66kg
29200           BEGALIEV, Kanatbek  KGZ    Men                   60 - 66kg
29201           GUENOT, Christophe  FRA    Men                   66 - 74kg
29202              YANAKIEV, Yavor  BUL    Men                   66 - 74kg
29203          KVIRKELIA, Manuchar  GEO    Men                   66 - 74kg
29204             CHANG, Yongxiang  CHN    Men                   66 - 74kg
29205                AVLUCA, Nazmi  TUR    Men                   74 - 84kg
29206             MINGUZZI, Andrea  ITA    Men                   74 - 84kg
29207                FODOR, Zoltan  HUN    Men                   74 - 84kg
29208              MAMBETOV, Asset  KAZ    Men                   84 - 96kg
29209                WHEELER, Adam  USA    Men                   84 - 96kg
29210           KHUSHTOV, Aslanbek  RUS    Men                   84 - 96kg
29211               ENGLICH, Mirko  GER    Men                   84 - 96kg
29212         MIZGAITIS, Mindaugas  LTU    Men                  96 - 120kg
29213              PATRIKEEV, Yuri  ARM    Men                  96 - 120kg
29214                LOPEZ, Mijain  CUB    Men                  96 - 120kg
29215               BAROEV, Khasan  RUS    Men                  96 - 120kg

      Event_gender   Medal
0                M    Gold
1                M  Silver
2                M  Bronze
3                M    Gold
4                M  Silver
5                M  Bronze
6                M    Gold
7                M  Silver
8                M  Bronze
9                M    Gold
10               M  Silver
11               M  Bronze
12               M  Bronze
13               M    Gold
14               M  Silver
15               M    Gold
16               M  Silver
17               M  Bronze
18               M    Gold
19               M  Silver
20               M  Bronze
21               M    Gold
22               M  Silver
23               M  Bronze
24               M    Gold
25               M  Silver
26               M  Bronze
27               M    Gold
28               M  Silver
29               M    Gold
...            ...     ...
29186            M  Bronze
29187            M    Gold
29188            M  Silver
29189            M  Bronze
29190            M  Bronze
29191            M    Gold
29192            M  Silver
29193            M  Bronze
29194            M  Bronze
29195            M    Gold
29196            M  Silver
29197            M  Bronze
29198            M  Bronze
29199            M    Gold
29200            M  Silver
29201            M  Bronze
29202            M  Bronze
29203            M    Gold
29204            M  Silver
29205            M  Bronze
29206            M    Gold
29207            M  Silver
29208            M  Bronze
29209            M  Bronze
29210            M    Gold
29211            M  Silver
29212            M  Bronze
29213            M  Bronze
29214            M    Gold
29215            M  Silver

[29216 rows x 10 columns]>